language: emacs

env:
  - EMACS=emacs23
  - EMACS=emacs24
  - EMACS=emacs-snapshot

matrix:
  allow_failures:
   - env: EMACS=emacs-snapshot

install:
  - if [ "$EMACS" = "emacs23" ]; then
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs23-nox;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24-nox;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi

script:
  - make test EMACS=$EMACS

notifications:
  email: false
