language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs # Emacs 24.3
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa # Emacs snapshot
  - sudo apt-get update
  - sudo apt-get install -y "${EMACS}"-nox
  # Install and bootstrap cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - cask install
script:
  - make test
