language: emacs-lisp
sudo: false
env:
  global:
    - PATH=$HOME/.cask/bin:$HOME/.evm/bin:$PATH
  matrix:
    # - EVM_EMACS=emacs-24.1-bin
    # - EVM_EMACS=emacs-24.2-bin
    - EVM_EMACS=emacs-24.3-bin
    - EVM_EMACS=emacs-24.4-bin
    - EVM_EMACS=emacs-24.5-bin
before_install:
  # evm install
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - cask --version
  - emacs --version
  # install deps for cask
  - cask
script:
  - pwd
  - make install test
