language: emacs-lisp
env:
  matrix:
    - EMACS=emacs-snapshot

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

script:
  - exec ./run-tests.sh