language: python
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get -yq update
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION)
  - sudo make -f emacs-travis.mk install_emacs EMACSCONFFLAGS='--with-xml2 CFLAGS=-O2 CXXFLAGS=-O2'
install:
  - pip install jupyter==$JUPYTER
env:
  - EMACS_VERSION=24.3 IPYCMD=jupyter JUPYTER=1.0.0
  - EMACS_VERSION=25.1-rc2 IPYCMD=jupyter JUPYTER=1.0.0
script: python tools/testein.py --emacs emacs --ipython $IPYCMD
 
