language: emacs-lisp
before_install:
  - git submodule --quiet update --init
  - sudo apt-get install -qq python-virtualenv
  - if [ "$EMACS" = "emacs24" ]; then
        sudo apt-get remove -qq emacs
        sudo apt-get install -qq emacs24
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
env:
  - EIN_TEST_TARGET=travis-ci-testein IPY_VERSION=3.0.0 EMACS=emacs24
matrix:
  allow_failures:
    IPY_VERSION=dev
    EMACS=emacs
    # EMACS=emacs-snapshot

script:
  make $EIN_TEST_TARGET IPY_VERSION=$IPY_VERSION
